### ISSUE TITLE
Album art fetch doesn't work

### ISSUE THREAD

**Issue by joelishness** [thomas-mc-work/most-possible-unattended-rip#12]
Problem Statement: Album art fetch doesn't work

Expected behavior:
1. Album art downloads
2. Album art embeds

Actual behavior:
1. Album art doesn't download
2. Album art doesn't embed

Log excerpt:
```
output directory /Audio-work/whipper/album/Will Smith - Big Willie Style (Several different stickers on outside of jewel case is common.) is a finished rip
### result: success (but couldn't find output folder for fetching cover art)
```

Thoughts:
1. Album art doesn't download
I think beets isn't even being called, based on the if-else statement:
```
    if cue_file_line=$(tr '\015' "\n" < "$log_file" | grep -E "$pattern"); then
        # ...
        # Use beets for image grabbing if it is available.
        # ...
        else
            fn_log "failed to find beets to fetch the cover art"
        fi
    else
        fn_log "result: success (but couldn't find output folder for fetching cover art)"

```
2. Album art doesn't embed
I guess this is intended.
Seems I should add the embed plugin to config `~/.config/beets/config.cover.yaml`?

From:
```
import:
    copy: no
    write: no
 
plugins: fetchart
```
To:
```
import:
    copy: no
    write: no
 
plugins: fetchart embedart
```
